#!/bin/bash
cd codes/Ro6afF/ 
git pull
cd ../../
cat .readme > README.md
git init
git add .
git commit
git remote add origin https://github.com/Alex-Tsvetanov/Informatics.git
git push -u origin master

