#!/bin/bash
cd codes/Ro6afF/ 
git pull
cd ../../
echo -e "#Школи, лагери, задачи и ришения на задачи по информатика\n##от Алекс Иванов Цветанов" > README.md
git init
git add .
git commit
git remote add origin https://github.com/Alex-Tsvetanov/Informatics.git
git push -u origin master

