#include<iostream>
using namespace std;
int main(){
int p,n,s,ans=0;
int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0;
cin>>p>>n>>s;
for(a=0;a<p;a++){
    if(n>1)
    for(b=0;b<p;b++){
        if(n>2)
        for(c=0;c<p;c++){
            if(n>3)
            for(d=0;d<p;d++){
                if(n>4)
                for(e=0;e<p;e++){
                    if(n>5)
                    for(f=0;f<p;f++){
                        if(n>6)
                        for(g=0;g<p;g++){
                            if(n>7)
                            for(h=0;h<p;h++){
                                if(n>8)
                                for(i=0;i<p;i++){
                                    if(n>9)
                                    for(j=0;j<p;j++){
                                        if(n>10)
                                        for(k=0;k<p;k++){
                                            if(n>11)
                                            for(l=0;l<p;l++){
                                                if(n>12)
                                                for(m=0;m<p;m++){
                                                    if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
                                                    ans++;
                                                }
                                            }
                                        }
                                            else{
                                                if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
                                                ans++;
                                            }
                                    }
                                        else{
                                            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
                                            ans++;
                                        }
                                }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
                                }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
                            }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
                        }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
                    }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
                }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
            }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
        }
        else{
            if(a+b+c+d+e+f+g+h+i+j+k+l+m<s)
            ans++;
        }
    }

cout<<ans<<endl;
return 0;
}
