  abcdefghijklmnopqrstuvwxyz
1 OOOOOOOOOOOOOOOOOOOOOOOOOO
2 OOOOOOOOOOOOOOOOOOOOOOOOOO
3 OOOOOOOOOOOOOOOOOOOOOOOOOO
4 OOOOOOOOOOOOOOOOOOOOOOOOOO
5 OOOOOOOOOOOOOOOOOOOOOOOOOO
6 OOOOOOOOOOOOOOOOOOOOOOOOOO
7 OOOOOOOOOOOOOOOOOOOOOOOOXO
8 OOOOOOOOOOOOOOOOOOOOOOOXOO
9 OOOOOOOOOOOOOOOOOOOOOOOOOH
