  abcdefghijklmnopqrstuvwxyz
1 OOOOOOOOOOOOOOOOOOOOOOOOOH
2 OOOOOOOOOOOOOOOOOOOOOOOXOO
3 OOOOOOOOOOOOOOOOOOOOOOOOXO
4 OOOOOOOOOOOOOOOOOOOOOOOOOO
5 OOOOOOOOOOOOOOOOOOOOOOOOOO
6 OOOOOOOOOOOOOOOOOOOOOOOOOO
