  abcdefghijklmnop
1 OOOOOOOOOOOOOOOO
2 OOOOOOOOOOOOOOOO
3 OOOOOOOOOOOOOOOO
4 OOOOOOOOOOOOOOOO
5 OOOOOOOXOXOOOOOO
6 OOOOOOXOOOXOOOOO
7 OOOOOOOOHOOOOOOO
8 OOOOOOXOOOXOOOOO
9 OOOOOOOXOXOOOOOO
10 OOOOOOOOOOOOOOOO
