  abcdefghijklmnopqrst
1 OOOOOOOOOOOOOOOOOOOO
2 OOOOOOOOOOOOOOOOOOOO
3 OXOXOOOOOOOOOOOOOOOO
4 XOOOXOOOOOOOOOOOOOOO
5 OOHOOOOOOOOOOOOOOOOO
6 XOOOXOOOOOOOOOOOOOOO
7 OXOXOOOOOOOOOOOOOOOO
8 OOOOOOOOOOOOOOOOOOOO
9 OOOOOOOOOOOOOOOOOOOO
10 OOOOOOOOOOOOOOOOOOOO
11 OOOOOOOOOOOOOOOOOOOO
12 OOOOOOOOOOOOOOOOOOOO
13 OOOOOOOOOOOOOOOOOOOO
14 OOOOOOOOOOOOOOOOOOOO
15 OOOOOOOOOOOOOOOOOOOO
