  abcdefghijklmnopqrstuvwxyz
1 OOOOOOOOOOHOOOOOOOOOOOOOOO
2 OOOOOOOOXOOOXOOOOOOOOOOOOO
3 OOOOOOOOOXOXOOOOOOOOOOOOOO
4 OOOOOOOOOOOOOOOOOOOOOOOOOO
5 OOOOOOOOOOOOOOOOOOOOOOOOOO
6 OOOOOOOOOOOOOOOOOOOOOOOOOO
7 OOOOOOOOOOOOOOOOOOOOOOOOOO
